"""
Convert transactions_1m (1) (1).csv -> public/transactions_synthetic.json

CSV columns : txn_id, sender_id, receiver_id, amount, timestamp, mode, is_fraud_pattern
App shape   : { id, from, to, amount, timestamp, type, flagged, riskScore }

Field conventions (shared with scripts/generate-synthetic-data.ts and the UI):
- type     : payment rail from the CSV "mode" column, lowercased
             (upi | imps | rtgs | neft) — matches the Transactions page filter.
- timestamp: source values are naive ISO (YYYY-MM-DDTHH:MM:SS, no offset) and
             are treated as UTC; normalized to "...Z" so JS Date parses them.
- amount   : kept as-is in rupees with paise (no rounding).

Strategy:
- Keep ALL fraud-pattern transactions (the mule networks)
- Sample plain (NONE) transactions down to a sane total (~100k) so the
  serverless function can parse the file quickly within memory limits.
- Derive riskScore from endpoint account risk + fraud pattern.

Downstream notes:
- scripts/recompute_transaction_scores.py post-processes this output file
  (recomputes riskScore / flagged), so counts here may drift from the artifact.
- Overwriting transactions_synthetic.json invalidates the transaction IDs
  referenced by public/alerts_synthetic.json (generated by
  scripts/generate-synthetic-data.ts); a stale-reference warning is printed
  below when that happens. Re-run generate-synthetic-data.ts to restore the
  matched pair.
"""

import csv
import json
import os
import random
import re

random.seed(42)

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(BASE, "transactions_1m (1) (1).csv")
ACCOUNTS_PATH = os.path.join(BASE, "public", "accounts_dataset.json")
OUT_PATH = os.path.join(BASE, "public", "transactions_synthetic.json")
ALERTS_PATH = os.path.join(BASE, "public", "alerts_synthetic.json")

TARGET_TOTAL = 100_000

PATTERN_BOOST = {
    "FANIN": 45,
    "PASSTHROUGH": 40,
    "CIRCULAR": 50,
    "FANOUT": 42,
}

with open(ACCOUNTS_PATH, "r", encoding="utf-8") as f:
    accounts = json.load(f)

risk_by_account = {}
for a in accounts:
    aid = str(a.get("account_id"))
    try:
        risk_by_account[aid] = float(a.get("risk_score", 10))
    except (TypeError, ValueError):
        risk_by_account[aid] = 10.0

pattern_counts = {}
total_rows = 0
none_rows = 0
known_senders = 0
known_receivers = 0
checked_overlap = 0

with open(CSV_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        total_rows += 1
        pat = (row.get("is_fraud_pattern") or "NONE").strip().upper()
        pattern_counts[pat] = pattern_counts.get(pat, 0) + 1
        if pat == "NONE":
            none_rows += 1
        if checked_overlap < 200_000:
            checked_overlap += 1
            if row["sender_id"] in risk_by_account:
                known_senders += 1
            if row["receiver_id"] in risk_by_account:
                known_receivers += 1

flagged_rows = total_rows - none_rows
print(f"CSV rows          : {total_rows}")
print(f"Pattern breakdown : {pattern_counts}")
print(f"ID overlap (first {checked_overlap:,} rows): senders {known_senders}/{checked_overlap}, receivers {known_receivers}/{checked_overlap}")

keep_none_target = max(0, TARGET_TOTAL - flagged_rows)
keep_none_ratio = min(1.0, keep_none_target / none_rows) if none_rows else 0.0
print(f"Flagged kept      : all {flagged_rows}")
print(f"NONE sampled      : {keep_none_ratio:.4f} ratio (~{int(none_rows * keep_none_ratio)})")

def make_risk_score(pat, sender_risk, receiver_risk):
    base = (sender_risk + receiver_risk) / 2.0
    if pat == "NONE":
        return round(min(55.0, base), 1)
    boost = PATTERN_BOOST.get(pat, 40)
    return round(min(97.0, base * 0.4 + boost + random.uniform(-5, 8)), 1)


NAIVE_TS_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?$")


def normalize_timestamp(raw, txn_id):
    """Normalize a CSV timestamp to UTC ISO-8601 ("...Z") for JS Date parsing.

    Source timestamps are naive (no offset) and are treated as UTC. Anything
    that is neither naive ISO nor already Z-suffixed is a hard error rather
    than a silently malformed timestamp downstream.
    """
    ts = raw.strip()
    if NAIVE_TS_RE.match(ts):
        return ts + ("Z" if "." in ts else ".000Z")
    if ts.endswith("Z"):
        return ts
    raise ValueError(f"{txn_id}: unexpected timestamp format {raw!r}")


out = []
with open(CSV_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        pat = (row.get("is_fraud_pattern") or "NONE").strip().upper()
        is_none = pat == "NONE"
        if is_none and random.random() > keep_none_ratio:
            continue
        sender_id = row["sender_id"]
        receiver_id = row["receiver_id"]
        sender_risk = risk_by_account.get(sender_id, 10.0)
        receiver_risk = risk_by_account.get(receiver_id, 10.0)
        ts = normalize_timestamp(row["timestamp"], row["txn_id"])
        out.append({
            "id": row["txn_id"],
            "from": sender_id,
            "to": receiver_id,
            "amount": float(row["amount"]),
            "timestamp": ts,
            "type": (row["mode"] or "upi").strip().lower(),
            "flagged": not is_none,
            "riskScore": make_risk_score(pat, sender_risk, receiver_risk),
        })

with open(OUT_PATH, "w", encoding="utf-8") as f:
    json.dump(out, f, separators=(",", ":"))

size_mb = os.path.getsize(OUT_PATH) / (1024 * 1024)
print(f"Written           : {len(out):,} transactions -> {OUT_PATH}")
print(f"Output size       : {size_mb:.1f} MB")

# Referential guard: alerts_synthetic.json is generated by
# scripts/generate-synthetic-data.ts against ITS OWN transaction IDs.
# Overwriting transactions_synthetic.json here orphans those references —
# warn loudly so the paired regeneration isn't forgotten.
if os.path.exists(ALERTS_PATH):
    with open(ALERTS_PATH, "r", encoding="utf-8") as f:
        alerts = json.load(f)
    new_ids = {t["id"] for t in out}
    stale_refs = sum(
        1
        for a in alerts
        for tid in a.get("transactions", [])
        if tid not in new_ids
    )
    if stale_refs:
        print(
            f"WARNING           : {stale_refs} alert transaction references no longer "
            f"exist in the rewritten transactions_synthetic.json. Re-run "
            f"scripts/generate-synthetic-data.ts to regenerate the matched pair."
        )
