"""
Convert transactions_1m (1) (1).csv -> public/transactions_synthetic.json

CSV columns : txn_id, sender_id, receiver_id, amount, timestamp, mode, is_fraud_pattern
App shape   : { id, from, to, amount, timestamp, type, flagged, riskScore }

Field conventions (shared with scripts/generate-synthetic-data.ts and the UI):
- type     : payment rail from the CSV "mode" column, lowercased
             (upi | imps | rtgs | neft) — matches the Transactions page filter.
             NOTE (D36): RBI mandates a ₹200,000 minimum for RTGS credits; the
             source CSV violates this on every RTGS row (observed min ₹28.86).
             The shipped artifact keeps raw amounts, so this converter only
             WARNS below instead of silently rewriting amounts — a full repair
             needs a source-CSV fix or an explicit amount-clamping decision.
- timestamp: source values are naive ISO (YYYY-MM-DDTHH:MM:SS, no offset)
             IST wall-clock times; tagged "+05:30" so the encoded instant is
             correct for JS Date parsing and the Asia/Kolkata-bucketed charts.
- amount   : kept as-is in rupees with paise (no rounding).

Strategy:
- Keep ALL fraud-pattern transactions (the mule networks)
- Sample plain (NONE) transactions down to a sane total (~100k) so the
  serverless function can parse the file quickly within memory limits.
- Derive riskScore from endpoint account risk + fraud pattern.

Downstream notes:
- scripts/recompute_transaction_scores.py post-processes this output file
  (recomputes riskScore / flagged), so counts here may drift from the artifact.
- Overwriting transactions_synthetic.json invalidates the transaction IDs
  referenced by public/alerts_synthetic.json (generated by
  scripts/generate_synthetic_data.py); a stale-reference warning is printed
  below when that happens. Re-run generate_synthetic_data.py to restore the
  matched pair.
"""

import csv
import json
import os
import random
import re
from datetime import datetime

random.seed(42)

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(BASE, "transactions_1m (1) (1).csv")
ACCOUNTS_PATH = os.path.join(BASE, "public", "accounts_dataset.json")
OUT_PATH = os.path.join(BASE, "public", "transactions_synthetic.json")
ALERTS_PATH = os.path.join(BASE, "public", "alerts_synthetic.json")

TARGET_TOTAL = 100_000

# D33: PATTERN_BOOST removed — pattern presence no longer inflates riskScore.
# Pattern membership still sets `flagged` (the dataset's labeling convention);
# the score itself derives only from endpoint account risk, so the trainer's
# features stop embedding the label.

with open(ACCOUNTS_PATH, "r", encoding="utf-8") as f:
    accounts = json.load(f)

risk_by_account = {}
for a in accounts:
    aid = str(a.get("account_id"))
    try:
        risk_by_account[aid] = float(a.get("risk_score", 10))
    except (TypeError, ValueError):
        risk_by_account[aid] = 10.0

pattern_counts = {}
total_rows = 0
none_rows = 0
known_senders = 0
known_receivers = 0
checked_overlap = 0

with open(CSV_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        total_rows += 1
        pat = (row.get("is_fraud_pattern") or "NONE").strip().upper()
        pattern_counts[pat] = pattern_counts.get(pat, 0) + 1
        if pat == "NONE":
            none_rows += 1
        if checked_overlap < 200_000:
            checked_overlap += 1
            if row["sender_id"] in risk_by_account:
                known_senders += 1
            if row["receiver_id"] in risk_by_account:
                known_receivers += 1

flagged_rows = total_rows - none_rows
print(f"CSV rows          : {total_rows}")
print(f"Pattern breakdown : {pattern_counts}")
print(f"ID overlap (first {checked_overlap:,} rows): senders {known_senders}/{checked_overlap}, receivers {known_receivers}/{checked_overlap}")

keep_none_target = max(0, TARGET_TOTAL - flagged_rows)
keep_none_ratio = min(1.0, keep_none_target / none_rows) if none_rows else 0.0
print(f"Flagged kept      : all {flagged_rows}")
print(f"NONE sampled      : {keep_none_ratio:.4f} ratio (~{int(none_rows * keep_none_ratio)})")

def make_risk_score(pat, sender_risk, receiver_risk):
    """RiskScore for one transaction.

    LABEL-LEAKAGE NOTE (D33): the fraud-pattern column IS the label source —
    every pattern row is shipped flagged=true. Boosting riskScore because a
    row is a pattern (the old PATTERN_BOOST floor) wrote the label into the
    feature the trainer then "predicts" from, inflating evaluation. Scores now
    derive ONLY from endpoint account risk; pattern membership still sets
    `flagged` (that is the dataset's labeling convention), but it no longer
    contaminates the numeric score.
    """
    base = (sender_risk + receiver_risk) / 2.0
    return round(min(97.0, base), 1)


TS_RE = re.compile(
    r"^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?)(Z|[+-]\d{2}:?\d{2})?$"
)


def normalize_timestamp(raw, txn_id):
    """Normalize a CSV timestamp to an offset-tagged ISO-8601 instant.

    Source timestamps are naive IST wall-clock times; they get a "+05:30"
    suffix so the encoded instant is correct for JS Date parsing and the
    Asia/Kolkata-bucketed charts. Values that already carry Z or an offset
    pass through unchanged. Shape and calendar validity are both checked so
    anything malformed (including bogus "garbageZ" strings or month 13) is a
    hard error rather than a silently broken timestamp downstream.
    """
    ts = raw.strip()
    match = TS_RE.match(ts)
    if not match:
        raise ValueError(f"{txn_id}: unexpected timestamp format {raw!r}")
    body, _offset = match.groups()
    fmt = "%Y-%m-%dT%H:%M:%S.%f" if "." in body else "%Y-%m-%dT%H:%M:%S"
    try:
        datetime.strptime(body, fmt)
    except ValueError:
        raise ValueError(f"{txn_id}: impossible calendar values in {raw!r}") from None
    return ts if _offset else ts + "+05:30"


out = []
with open(CSV_PATH, "r", encoding="utf-8", newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        pat = (row.get("is_fraud_pattern") or "NONE").strip().upper()
        is_none = pat == "NONE"
        if is_none and random.random() > keep_none_ratio:
            continue
        sender_id = row["sender_id"]
        receiver_id = row["receiver_id"]
        sender_risk = risk_by_account.get(sender_id, 10.0)
        receiver_risk = risk_by_account.get(receiver_id, 10.0)
        ts = normalize_timestamp(row["timestamp"], row["txn_id"])
        out.append({
            "id": row["txn_id"],
            "from": sender_id,
            "to": receiver_id,
            "amount": float(row["amount"]),
            "timestamp": ts,
            "type": (row["mode"] or "upi").strip().lower(),
            "flagged": not is_none,
            "riskScore": make_risk_score(pat, sender_risk, receiver_risk),
        })

# Contract guard: riskScore is consumed as a 0-100 scale everywhere downstream
# (UI badges/filters, recompute_transaction_scores.py's *100 step).
assert all(0 <= t["riskScore"] <= 100 for t in out), \
    "riskScore drifted off the 0-100 scale"

with open(OUT_PATH, "w", encoding="utf-8") as f:
    json.dump(out, f, separators=(",", ":"))

size_mb = os.path.getsize(OUT_PATH) / (1024 * 1024)
print(f"Written           : {len(out):,} transactions -> {OUT_PATH}")
print(f"Output size       : {size_mb:.1f} MB")

# Referential guard: alerts_synthetic.json is generated by
# scripts/generate_synthetic_data.py against the SHIPPED transaction ids.
# Overwriting transactions_synthetic.json here orphans those references —
# warn loudly so the paired regeneration isn't forgotten.
if os.path.exists(ALERTS_PATH):
    with open(ALERTS_PATH, "r", encoding="utf-8") as f:
        alerts = json.load(f)
    new_ids = {t["id"] for t in out}
    stale_refs = sum(
        1
        for a in alerts
        for tid in a.get("transactions", [])
        if tid not in new_ids
    )
    if stale_refs:
        print(
            f"WARNING           : {stale_refs} alert transaction references no longer "
            f"exist in the rewritten transactions_synthetic.json. Re-run "
            f"scripts/generate_synthetic_data.py to regenerate the matched pair."
        )

# D36 guard: RBI requires >= INR 200,000 for RTGS. The source CSV violates this
# on every RTGS row; report it rather than silently shipping an impossible rail.
rtgs_rows = [t for t in out if t.get("type") == "rtgs"]
rtgs_violations = sum(1 for t in rtgs_rows if float(t["amount"]) < 200_000)
if rtgs_rows:
    print(
        f"WARNING (D36)     : {rtgs_violations}/{len(rtgs_rows)} RTGS rows are below "
        f"the RBI 200000 minimum (min amount {min(float(t['amount']) for t in rtgs_rows)}). "
        f"Amounts kept as-is; fixing requires a source-CSV repair decision."
    )
